### ISSUE TITLE
Does virtual1 patch for xserver-xorg-video-intel work on Ubuntu 13.04?

### ISSUE THREAD

**Issue by micheled** [krlmlr-archive/xserver-xorg-video-intel#1]
I am new to github so I apologize in case this is not the right place to post this.

I run Ubuntu 13.04 on Lenovo Thinkpad W530 and installed this patched package, namely the output of "dpkg -s xserver-xorg-video-intel | grep Version" is "Version: 2:2.21.6-0ubuntu4+virtual1".

Nevertheless, after reboot I have no virtual screen, namely the output of "xrandr" is "LVDS1 connected... VGA1 disconnected..." (where dots replace lengthy but probably not-so-informative stuff, no VIRTUAL1 is present).

The same happens if I patch and compile the source by myself, as explained e.g. here http://sagark.org/optimal-ubuntu-graphics-setup-for-thinkpads.

Am I doing something wrong? Thanks a lot.

**Comment by krlmlr** [comment]
This is for Ubuntu 13.04 only at the moment. I have written the steps how I got this working [here](http://askubuntu.com/a/303897/30266).

Unfortunately, I don't know much more than that, so I'm closing this issue.

**Comment by micheled** [comment]
Thank you very much for the link, I managed to make it work. I was missing the "Edit xorg.conf.nvidia" part as I was following instructions for previous versions of Ubuntu.

**Comment by krlmlr** [comment]
Glad it works for you now.
